/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin processor.

  ==============================================================================
*/

#include "PluginProcessor.h"
#include "PluginEditor.h"
#include "HrtfFilter.h"


//==============================================================================
AuralizerAudioProcessor::AuralizerAudioProcessor()
{
    preGain_ = 1.0f;
    angle_ = 0.0f;
    speed_ = 1.0f;
    outputGain_ = 1.0f;
    automation_ = 0.0f;
    bypass_ = 0.0f;
    
    filter_.set();
}

AuralizerAudioProcessor::~AuralizerAudioProcessor()
{
}

//==============================================================================
const String AuralizerAudioProcessor::getName() const
{
    return JucePlugin_Name;
}

int AuralizerAudioProcessor::getNumParameters()
{
    return kNumParameters;
}

float AuralizerAudioProcessor::getParameter (int index)
{
    switch (index)
    {
        case kPreGainParam:
            return preGain_;
        case kAngleParam:
            return angle_;
        case kSpeedParam:
            return speed_;
        case kOutputGainParam:
            return outputGain_;
        case kAutomationParam:
            return automation_;
        case kBypassParam:
            return bypass_;
        default:
            return 0.0f; // invalid index
    }
}

void AuralizerAudioProcessor::setParameter (int index, float newValue)
{
    switch (index)
    {
        case kPreGainParam:
            preGain_ = newValue;
            break;
        case kAngleParam:
            angle_ = newValue;
            break;
        case kSpeedParam:
            speed_ = newValue;
            break;
        case kOutputGainParam:
            outputGain_ = newValue;
            break;
        case kAutomationParam:
            automation_ = newValue;
            break;
        case kBypassParam:
            bypass_ = newValue;
            break;
        default:
            return;        
    }
}

const String AuralizerAudioProcessor::getParameterName (int index)
{
    switch (index)
    {
        case kPreGainParam:
            return "Pre Gain";
        case kAngleParam:
            return "Source Angle";
        case kSpeedParam:
            return "Source Speed";
        case kOutputGainParam:
            return "Output Gain";
        case kAutomationParam:
            return "Source Automation";
        case kBypassParam:
            return "Bypass";
        default:
            return String();  
    }
}

const String AuralizerAudioProcessor::getParameterText (int index)
{
    return String();
}

const String AuralizerAudioProcessor::getInputChannelName (int channelIndex) const
{
    return String (channelIndex + 1);
}

const String AuralizerAudioProcessor::getOutputChannelName (int channelIndex) const
{
    return String (channelIndex + 1);
}

bool AuralizerAudioProcessor::isInputChannelStereoPair (int index) const
{
    return true;
}

bool AuralizerAudioProcessor::isOutputChannelStereoPair (int index) const
{
    return true;
}

bool AuralizerAudioProcessor::acceptsMidi() const
{
   #if JucePlugin_WantsMidiInput
    return true;
   #else
    return false;
   #endif
}

bool AuralizerAudioProcessor::producesMidi() const
{
   #if JucePlugin_ProducesMidiOutput
    return true;
   #else
    return false;
   #endif
}

bool AuralizerAudioProcessor::silenceInProducesSilenceOut() const
{
    return false;
}

double AuralizerAudioProcessor::getTailLengthSeconds() const
{
    return 0.0;
}

int AuralizerAudioProcessor::getNumPrograms()
{
    return 1;   // NB: some hosts don't cope very well if you tell them there are 0 programs,
                // so this should be at least 1, even if you're not really implementing programs.
}

int AuralizerAudioProcessor::getCurrentProgram()
{
    return 0;
}

void AuralizerAudioProcessor::setCurrentProgram (int index)
{
}

const String AuralizerAudioProcessor::getProgramName (int index)
{
    return String();
}

void AuralizerAudioProcessor::changeProgramName (int index, const String& newName)
{
}

//==============================================================================
void AuralizerAudioProcessor::prepareToPlay (double sampleRate, int samplesPerBlock)
{
    
}

void AuralizerAudioProcessor::releaseResources()
{
    // When playback stops, you can use this as an opportunity to free up any
    // spare memory, etc.
}

void AuralizerAudioProcessor::processBlock (AudioSampleBuffer& buffer, MidiBuffer& midiMessages)
{
    // check conditions
    if (getSampleRate()!= 44100)
        return;
    else if (bypass_ == 1)
        return;
    else
    {
        const int bufferLength = buffer.getNumSamples();
        if (bufferLength < 100)
            return;
        
        // get pointers
        float* inLeft = buffer.getWritePointer(0);
        float* inRight = buffer.getWritePointer(1);
        
        // pre gain
        buffer.applyGain(preGain_);
        
        // downmix stereo input to mono
        if (getNumInputChannels() == 2)
        {
            buffer.addFrom(0, 0, inRight, bufferLength);
            buffer.applyGain(0.5f);
        }
        
        // filtering
        filter_.setAngle(angle_);
        filter_.ClockProcess(inLeft, inRight, bufferLength);
        
        // output gain
        buffer.applyGain(outputGain_);
        
    
        // automation control
        if (automation_ == 1)
        {
            if (angle_ + speed_ < 359)
                angle_ += speed_;
            else
                angle_ += speed_ - 359;
        }
    }
}

//==============================================================================
bool AuralizerAudioProcessor::hasEditor() const
{
    return true; // (change this to false if you choose to not supply an editor)
}

AudioProcessorEditor* AuralizerAudioProcessor::createEditor()
{
    return new AuralizerAudioProcessorEditor (*this);
}

//==============================================================================
void AuralizerAudioProcessor::getStateInformation (MemoryBlock& destData)
{
    // You should use this method to store your parameters in the memory block.
    // You could do that either as raw data, or use the XML or ValueTree classes
    // as intermediaries to make it easy to save and load complex data.
}

void AuralizerAudioProcessor::setStateInformation (const void* data, int sizeInBytes)
{
    // You should use this method to restore your parameters from this memory block,
    // whose contents will have been created by the getStateInformation() call.
}

//==============================================================================
// This creates new instances of the plugin..
AudioProcessor* JUCE_CALLTYPE createPluginFilter()
{
    return new AuralizerAudioProcessor();
}
